### ISSUE TITLE
missing metrics

### ISSUE THREAD

**Issue by oferzi23** [fastly/fastly-exporter#14]
hello, 

correct me if i missed something big here, but i look at the fastly historical stats api documentation [here][https://docs.fastly.com/api/stats], i see many metrics which are not exported to my prom server such as status_5xx. did i miss something or is this currently not supported?

**Comment by peterbourgon** [comment]
This exporter is a bridge to the [Fastly Real-time Analytics](https://docs.fastly.com/api/analytics) API, which is similar to but different from the historical stats API. But, we definitely report e.g. [status_5xx](https://github.com/peterbourgon/fastly-exporter/blob/master/process.go#L72). If you don't see it in your Prometheus metrics, it's either because (a) there's a bug, or (b) your service hasn't seen any 5xx in the recent past.

Does this answer the question?

**Comment by mrnetops** [comment]
@oferzi23 status_5xx is reported via status_group_total{status_group="5xx"}
