### ISSUE TITLE
Add datcenters API enricment

### ISSUE THREAD

**Issue by SuperQ** [fastly/fastly-exporter#79]
There's a [`/datacenters`](https://developer.fastly.com/reference/api/utils/pops/#list-pops) API endpoint that has a bunch of additional info that could be useful as labels.

For example, the `group` might be a nice label to aggregate over.

**Comment by peterbourgon** [comment]
There's lots of metadata that would be interesting and/or useful to expose in the fastly-exporter. But because the /datacenters API is distinct from the the real-time analytics API, we can't attach any of the metadata from the former directly to the metrics derived from the latter. Would it be acceptable if this association were provided in separate e.g. gauge metrics?

**Comment by SuperQ** [comment]
Sure, `fastly_datacenter_info` would be fine, you can `group_left` join the data in PromQL.
